### ISSUE TITLE
Support for IMediaSeeking SetPositions()

### ISSUE THREAD

**Issue by clsid2** [v0lt/ImageSourceFilter#1]
Can you add support for setting the duration through SetPositions() ?

Then player can control how long an image is displayed. The Generate Still Video filter from Windows has same ability.

Example:
```
STDMETHODIMP CFGManagerPlayer::ConnectDirect(IPin* pPinOut, IPin* pPinIn, const AM_MEDIA_TYPE* pmt)
{
    CAutoLock cAutoLock(this);

    CLSID pin_clsid = GetCLSID(pPinOut);
    if (pin_clsid == CLSID_StillVideo || pin_clsid == CLSID_MPCImageSource) {
        CComQIPtr<IMediaSeeking> pMS = pPinOut;
        if (pMS) {
            const CAppSettings& s = AfxGetAppSettings();
            if (s.iStillVideoDuration > 0) {
                REFERENCE_TIME rtCur = 0;
                REFERENCE_TIME rtDur = s.iStillVideoDuration * 10000000LL;
                pMS->SetPositions(&rtCur, AM_SEEKING_AbsolutePositioning, &rtDur, AM_SEEKING_AbsolutePositioning);
            }
        }
    }

    return __super::ConnectDirect(pPinOut, pPinIn, pmt);
}
```

**Comment by v0lt** [comment]
I find it very strange to be able to set the duration for the source filter. I don't understand how this is even possible. What should the source filter do when the file is 10 seconds long and the player asks for 2 hours?

I'll take a look sometime...

**Comment by v0lt** [comment]
Try [MpcImageSource-0.2.4.102_git2022.05.13-8db810a](https://disk.yandex.ru/d/jQYapx92Izm7gw).

**Comment by clsid2** [comment]
Working good.

This function is mainly for cases where something does not have a duration by itself, such as still image. If certain content, such as gif, does have a valid duration by itself, then you could ignore the duration requested by the player.

**Comment by v0lt** [comment]
Also check out the new version.
[MpcImageSource-0.2.4.103_git2022.05.14-301367d](https://disk.yandex.ru/d/jQYapx92Izm7gw)

**Comment by clsid2** [comment]
Here is very short gif:
[shortgif.zip](https://github.com/v0lt/ImageSourceFilter/files/8692939/shortgif.zip)

Generate Still Video will play it as a loop until it reaches the duration that was set (or infinite loop if no duration set).

Maybe you can further improve the code to do this:
- Image has duration 0. Repeat until duration suggested by player.
- If duration of image (GIF/Webp/etc) longer than duration suggested by player. Use original duration of image.
- If duration of image shorter than duration suggested by player. Loop image. But only do full repeats. So for example image duration is 3 seconds, and suggested duration is 10 seconds. Then repeat 3 times and use 9 seconds as total duration. If image is 6 seconds, then, repeat just 1 time and keep total duration at 6. So never do a partial loop.

**Comment by v0lt** [comment]
> Here is very short gif:
> [shortgif.zip](https://github.com/v0lt/ImageSourceFilter/files/8692939/shortgif.zip)

ImageSourceFilter does not support animated and multipage images.
I didn't even add GIF support on purpose. I won't be able to do better than "Generate Still Video" in the near future.

**Comment by v0lt** [comment]
If you force an ImageSourceFilter in the player's external filters, the GIF file will be opened by this filter. But this is a coincidence.

[List of files](https://github.com/v0lt/ImageSourceFilter/blob/5c9328dfbc84f45fd90541d63daa51e6c1b0ee8b/Source/dllmain.cpp#L57) that can be opened in ImageSourceFilter without forcing.

**Comment by v0lt** [comment]
I also see that in MPC-HC there is a higher priority for registering a source filter by extension, compared to registering by signature. This causes "Generate Still Video" to open JPEGs and BMPs even if you raise the ImageSourceFilter priority on the system to the maximum. And only forcing the filter in the player will help.

[An example of a simple solution to this problem](https://github.com/Aleksoid1978/MPC-BE/commit/c5b0bad77c8117fa470c62851038380a4083816c).
