### ISSUE TITLE
Some text on the properties window cannot be seen due to DPI

### ISSUE THREAD

**Issue by xLn2** [v0lt/ImageSourceFilter#2]
My display settings are: 1920x1080 ,125%DPi

![mpc-hc64_M4LcmSURZS](https://github.com/v0lt/ImageSourceFilter/assets/3073922/550feedf-dffe-4c8c-acf7-41414ab9cceb)

Thanks for project.

**Comment by v0lt** [comment]
Thank you.
Fixed in MpcImageSource 0.2.8.148.
commit df7f8b7.
